version: '3'

services:

  nginx:
    image: nginx:1.17.10
    container_name: dsp_nginx
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - dspback
      - catalog

  dspback:
    image: dspback
    container_name: dspback
    volumes:
      - ./dspback:/dspback
    entrypoint: bash dev-entrypoint.sh
    env_file: .env
    build:
      context: ./dspback
      dockerfile: Dockerfile-dev
    ports:
      - 5002:5002
    restart: on-failure
    depends_on:
      - postgres

  catalog:
    image: catalog
    container_name: catalog
    volumes:
      - ./dspback-django:/app
      - ./OCGbuildingBlockTest:/OCGbuildingBlockTest
    env_file: .env
    build:
      context: ./dspback-django
      dockerfile: Dockerfile-dev
    ports:
      - 5003:5003
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: dsp_postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dspback/postgres-data:/var/lib/postgresql/data
      - ./scripts/init-catalog-db.sh:/docker-entrypoint-initdb.d/init-catalog-db.sh
    environment:
      - POSTGRES_USER=dsp
      - POSTGRES_PASSWORD=dsp
      - POSTGRES_DB=dsp
