version: '3'

services:

  nginx:
    image: nginx:1.23.1
    container_name: dsp_nginx
    volumes:
      - ./nginx/nginx-demo.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - dspfront
      - dspback
      - catalog

  dspfront:
    image: dspfront
    container_name: dspfront
    build:
      context: ./dspfront
      dockerfile: Dockerfile
    environment:
      - VITE_APP_API_URL=http://${DEMO_HOST:-localhost}
      - VITE_APP_URL=http://${DEMO_HOST:-localhost}
    restart: on-failure

  dspback:
    image: dspback
    container_name: dspback
    env_file: .env
    build:
      context: ./dspback
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - postgres

  catalog:
    image: catalog
    container_name: catalog
    volumes:
      - ./OCGbuildingBlockTest:/OCGbuildingBlockTest
    env_file: .env
    build:
      context: ./dspback-django
      dockerfile: Dockerfile-dev
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn catalog.wsgi:application --bind 0.0.0.0:5003 --workers 2"
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: dsp_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-catalog-db.sh:/docker-entrypoint-initdb.d/init-catalog-db.sh
    environment:
      - POSTGRES_USER=dsp
      - POSTGRES_PASSWORD=dsp
      - POSTGRES_DB=dsp

volumes:
  pgdata:
